#pragma once

#define AUTOSUPPORT_DEV_MODE // this should be commented out before releasing a new version!

#ifdef AUTOSUPPORT_DEV_MODE

#define AUTOSUPPORT_DEV_LOGGING
#define AUTOSUPPORT_DEV_KEEP_EMPTY_PROXIES
#define AUTOSUPPORT_DRAW_DEBUG_SHAPES

#endif

#define AUTOSUPPORT_BUILD_SPACE_TOLERANCE 1.f
#define AUTOSUPPORT_TRANSFORM_EQUALITY_TOLERANCE 1.f